# Generated by Django 5.2.4 on 2025-07-31 10:09

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TimeField()),
                ('evidence_link', models.URLField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scammer_name', models.CharField(max_length=100)),
                ('socials', models.JSONField(blank=True, default=list, null=True)),
                ('incidence_description', models.TextField()),
                ('county', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('isglobal', models.BooleanField(default=False)),
                ('evidence_drive_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_app.supportpost')),
            ],
        ),
    ]
