# Generated by Django 5.2.4 on 2025-07-31 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scampost',
            name='supports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_evidence', to='reports_app.supportpost'),
        ),
    ]
