# Generated by Django 5.2.4 on 2025-07-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0002_alter_scampost_supports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportpost',
            name='description',
            field=models.TextField(),
        ),
    ]
