# Generated by Django 5.2.4 on 2025-08-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0004_remove_scampost_supports_supportpost_supports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportpost',
            old_name='supports',
            new_name='scampost',
        ),
    ]
