# Generated by Django 5.2.4 on 2025-08-01 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0005_rename_supports_supportpost_scampost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scampost',
            old_name='county',
            new_name='county_name',
        ),
    ]
