# Generated by Django 5.2.4 on 2025-08-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0006_rename_county_scampost_county_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scampost',
            old_name='county_name',
            new_name='country',
        ),
    ]
