# Generated by Django 5.2.4 on 2025-08-29 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0012_alter_downvote_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='reports_app.scampost'),
        ),
    ]
